sudo: required
services:
        - docker

before_install:
        - docker build -t manikanta513/frontend -f Dockerfile.dev .

script:
        - docker run manikanta513/frontend npm run test -- --coverage
