sudo: required
services:
        - docker

before_install:
        - docker build -t manikanta513/frontend -f Dockerfile.dev .

script:
        - docker run manikanta513/frontend npm run test -- --coverage



deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "frontend"
        env: "frontend-env"
        bucket_name: "elasticbeanstalk-ap-south-1-457180139478"
        bucket_path: "frontend"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"


